services:

  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DATABASE: ecommerce
    ports:
      - "5432:5432"
