version: '3.9'

services:
  db-postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DATABASE: ecommerce
    ports:
      - "5432:5432"
  # redis:
  #   image: redis
  #   command: redis-server --requirePass nicolas0708
  #   ports:
  #     - "6379:6379"